import { Geist, Geist_Mono, Inter, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Header from "./components/Header.js";
import Footer from "./components/Footer.js";
import { UserProvider, UserContext } from "./Context/UserContext.js";
import { Toaster } from "react-hot-toast";
import MuiThemeProvider from "./ThemeProvider";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter-mono",
});
const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-be-vietnam-pro",
});

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={beVietnamPro.variable}>
      <body className={`${beVietnamPro.className} antialiased bg-[#f5f5f5]`}>
        <div className="relative flex size-full min-h-screen flex-col bg-[#f5f5f5] group/design-root overflow-x-hidden">
          <div className="layout-container flex h-full grow flex-col">
            {/* <MuiThemeProvider> */}
            <UserProvider>
              <Header />
              <div className=" sm:w-[90%] md:w-[80%] lg:w-[75%] mx-auto">
                {children}
              </div>
              <Footer />
              <Toaster
                toastOptions={{
                  className: "",
                  style: {
                    fontSize: "13px",
                  },
                }}
              />
            </UserProvider>
            {/* </MuiThemeProvider> */}
          </div>
        </div>
      </body>
    </html>
  );
}
